### ISSUE TITLE
Download crash after a while

### ISSUE THREAD

**Issue by spodlesny** [nishad/udemy-dl#12]
Script just crash on this link every time. 

```bash
Downloading 019 Modules.mp4  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39.0M  100 39.0M    0     0  5407k      0  0:00:07  0:00:07 --:--:-- 7747k

Downloading 020 Parameters.mp4  
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 220, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 161, in udemy_dl
    get_video(directory, filename, video['video_url'])
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 137, in get_video
    download(link, filename)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/download.py", line 11, in download
    if 'youtube.com' in link:
TypeError: argument of type 'NoneType' is not iterable
```

It's Flask course (https://www.udemy.com/python-flask-course) and I have a newest version of udemy-dl

**Comment by mukhlesur-millon** [comment]
have you any free course that crash...

**Comment by spodlesny** [comment]
I downloaded another paid course from Udemy and without problems.

**Comment by mukhlesur-millon** [comment]
your issue should fix with it.
python -m pip install https://github.com/mukhlesur-millon/udemy-dl/zipball/master
if it is fixed then close it.

**Comment by spodlesny** [comment]
It works, thank you
