### ISSUE TITLE
[BUG] Error while downloading videos

### ISSUE THREAD

**Issue by abhigenie92** [nishad/udemy-dl#122]
```
abhishek PySpark $ udemy-dl -v
udemy-dl 0.2.1
```
Version : **0.2.1**
Operation System: Kubuntu 16.04
It download the first set of videos but then the following error came up:

```
Downloading attached files
Traceback (most recent call last):
  File "/home/abhishek/anaconda3/bin/udemy-dl", line 7, in <module>
    main()
  File "/home/abhishek/anaconda3/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/home/abhishek/anaconda3/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 706, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/home/abhishek/anaconda3/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 624, in get_data
    get_attached_file(file_dir, attached_info)
  File "/home/abhishek/anaconda3/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 523, in get_attached_file
    for element in attached_json['download_urls']['File']:
KeyError: 'File'

```
 This might be related to https://github.com/nishad/udemy-dl/issues/109. But I have youtube-dl already installed.
A similar such issue has no reponse https://github.com/nishad/udemy-dl/issues/98

**Comment by mukhlesur-millon** [comment]
@abhigenie92  **All issues should contain mandatory check lists, version number and proper prefix for the subject line**

you are using an older version. this was fixed.

**Comment by abhigenie92** [comment]
Sorry for not including the version number. It seems to be latest though.
```
abhishek ~ $ udemy-dl --version
udemy-dl 0.2.1
abhishek ~ $ pip install udemy-dl --upgrade
Requirement already up-to-date: udemy-dl in ./anaconda3/lib/python3.5/site-packages
Requirement already up-to-date: requests in ./anaconda3/lib/python3.5/site-packages (from udemy-dl)
Requirement already up-to-date: future in ./anaconda3/lib/python3.5/site-packages (from udemy-dl)
Requirement already up-to-date: colorlog in ./anaconda3/lib/python3.5/site-packages (from udemy-dl)
Requirement already up-to-date: unicode-slugify in ./anaconda3/lib/python3.5/site-packages (from udemy-dl)
Requirement already up-to-date: six in ./anaconda3/lib/python3.5/site-packages (from unicode-slugify->udemy-dl)
Requirement already up-to-date: unidecode in ./anaconda3/lib/python3.5/site-packages (from unicode-slugify->udemy-dl)

```

**Comment by mukhlesur-millon** [comment]
[update from here](https://github.com/nishad/udemy-dl/wiki/Installing-development-version)

**Comment by abhigenie92** [comment]
This is fixes it.
