### ISSUE TITLE
[BUG] [CRITICAL-51] aria2c not found. Downloading with builtin downloader

### ISSUE THREAD

**Issue by Brunaldo** [nishad/udemy-dl#123]
Version : **0.2.1**

---

{issue content here, replace this line with your issue content}
```
[CRITICAL-51] aria2c not found. Downloading with builtin downloader
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/download.py", line 38, in download
    aria2c_dl(link, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/download.py", line 86, in aria2c_dl
    subprocess.call(command)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'aria2c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1237, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/__main__.py", line 8, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 706, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 609, in get_data
    get_video(link, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 570, in get_video
    check_downloaded(link, filename, downloader, tmp_file=tmp_file)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 582, in check_downloaded
    download_status = download(link, tmp_file, update_progress, downloader_name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/download.py", line 52, in download
    urlopen_dl(link, filename, update_progress)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/download.py", line 113, in urlopen_dl
    response = urlopen(link)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
```

I'm trying to download a paid course for which I have paid for. Using sudo also gives the same error, I'm on El Capitan version 10.11.5

Downloaded aria2 here https://github.com/aria2/aria2/releases/tag/release-1.24.0 as well

**Comment by tobias-p** [comment]
could you please post the command you used?

**Comment by Brunaldo** [comment]
Hi there

I restarted my mac after downloading aria2 and now it's working with the command
`udemy-dl -u user@domain.com -p $ecRe7w0rd https://www.udemy.com/COURSE_NAME
`

**Comment by dushyantbangal** [comment]
I'm getting this issue in `udemy-dl 0.2.2-alpha.2`

`[CRITICAL-50] aria2c not found. Downloading with builtin downloader`
