### ISSUE TITLE
getting Error long lectures name

### ISSUE THREAD

**Issue by jaan143** [nishad/udemy-dl#124]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked that the issue I'm posting isn't already reported.
- [x ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Hi nishad
its not downloading courses which have long lecture names 
i tried many courses but cant get
here you can check logs

[INFO-120] Trying to log in ...
[INFO-150] Login success.
[INFO-182] Found course id: 532836
Getting course data: 100.00% [====================] Done

Downloading Video: 001 Welcome from Doc Brown to Usher You Into A Financially Happier Life Right Now

[CRITICAL-45] aria2c not found. Downloading with builtin downloader
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 978, in emit
    msg = self.format(record)
  File "C:\Python34\lib\logging\__init__.py", line 828, in format
    return fmt.format(record)
  File "C:\Python34\lib\site-packages\colorlog\colorlog.py", line 129, in format
    message = super(ColoredFormatter, self).format(record)
  File "C:\Python34\lib\logging\__init__.py", line 573, in format
    record.exc_text = self.formatException(record.exc_info)
  File "C:\Python34\lib\logging\__init__.py", line 523, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "C:\Python34\lib\traceback.py", line 169, in print_exception
    for line in _format_exception_iter(etype, value, tb, limit, chain):
  File "C:\Python34\lib\traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "C:\Python34\lib\traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
Call stack:
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 48, in logging_exception
    logger.exception(''.join(traceback.format_exception(type_, value, tb)))
Message: 'Traceback (most recent call last):\n  File "C:\\Python34\\lib\\site-packages\\udemy_dl\\download.py", line 30, in download\n    aria2c_dl(link, filename)\n  File "C:\\Python34\\lib\\site-packages\\udemy_dl\\download.py", line 80, in aria2c_dl\n    subprocess.call(command)\n  File "C:\\Python34\\lib\\subprocess.py", line 537, in call\n    with Popen(*popenargs, **kwargs) as p:\n  File "C:\\Python34\\lib\\subprocess.py", line 859, in __init__\n    restore_signals, start_new_session)\n  File "C:\\Python34\\lib\\subprocess.py", line 1112, in _execute_child\n    startupinfo)\nFileNotFoundError: [WinError 2] The system cannot find the file specified\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "C:\\Python34\\lib\\runpy.py", line 170, in _run_module_as_main\n    "__main__", mod_spec)\n  File "C:\\Python34\\lib\\runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "C:\\Python34\\lib\\site-packages\\udemy_dl\\__main__.py", line 8, in <module>\n    main()\n  File "C:\\Python34\\lib\\site-packages\\udemy_dl\\udemy_dl.py", line 871, in main\n    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)\n  File "C:\\Python34\\lib\\site-packages\\udemy_dl\\udemy_dl.py", line 735, in udemy_dl\n    get_data(directory, filename, data_url, data_type, attached_info, caption_list)\n  File "C:\\Python34\\lib\\site-packages\\udemy_dl\\udemy_dl.py", line 638, in get_data\n    get_video(link, filename)\n  File "C:\\Python34\\lib\\site-packages\\udemy_dl\\udemy_dl.py", line 597, in get_video\n    check_downloaded(link, filename, downloader, tmp_file=tmp_file)\n  File "C:\\Python34\\lib\\site-packages\\udemy_dl\\udemy_dl.py", line 611, in check_downloaded\n    download_status = download(link, tmp_file, update_progress, downloader_name)\n  File "C:\\Python34\\lib\\site-packages\\udemy_dl\\download.py", line 46, in download\n    requests_dl(link, filename, update_progress)\n  File "C:\\Python34\\lib\\site-packages\\udemy_dl\\download.py", line 112, in requests_dl\n    with open(filename, \'wb\') as file:\nFileNotFoundError: [Errno 2] No such file or directory: \'654321-001 Welcome from Doc Brown to Usher You Into A Financially Happier Life Right Now.mp4.tmp\'\n'
Arguments: ()

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Comment by jaan143** [comment]
hi plz reopen my issue and check plz

**Comment by nishad** [comment]
There is already an option as

```
--safe-file-names     Use safe cross-platform filenames
```

You can try downloading with that.

**Comment by jaan143** [comment]
Hi Sir
i tried with this command but getting same error

python -m udemy_dl -u *****@yahoo.com -p ***** --safe-file-names https://www.udemy.com/take-the-bulletproof-401k-super-charger-rat-race-off-ramp/

**Comment by jaan143** [comment]
hi Dear
Today i am getting this issue also and i tried many courses but getting the same
it was working fine till yesterday but not today
the same i got
plz fix this issue
