### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Brunaldo** [nishad/udemy-dl#127]
**udemy-dl 0.2.1**

Paid course I'm trying to download (I have paid for it): https://www.udemy.com/the-complete-internet-security-privacy-course-volume-1/
---

```
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
7d40f4|ERR |       0B/s|/Users/user/the-complete-internet-security-privacy-course-volume-1/01 Introduction/654321-003 Target Audience.mp4.tmp

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 706, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 609, in get_data
    get_video(link, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 570, in get_video
    check_downloaded(link, filename, downloader, tmp_file=tmp_file)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 584, in check_downloaded
    os.rename(tmp_file, filename)
FileNotFoundError: [Errno 2] No such file or directory: '654321-003 Target Audience.mp4.tmp' -> '003 Target Audience.mp4'
```

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
