### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Brunaldo** [nishad/udemy-dl#128]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **udemy-dl 0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

```
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
dbadd4|ERR |       0B/s|/Users/user/the-complete-internet-security-privacy-course-volume-1/01 Introduction/654321-003 Target Audience.mp4.tmp

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 706, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 609, in get_data
    get_video(link, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 570, in get_video
    check_downloaded(link, filename, downloader, tmp_file=tmp_file)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/udemy_dl/udemy_dl.py", line 584, in check_downloaded
    os.rename(tmp_file, filename)
FileNotFoundError: [Errno 2] No such file or directory: '654321-003 Target Audience.mp4.tmp' -> '003 Target Audience.mp4'

```

**Comment by nishad** [comment]
It seems like an issue with `aria2c`, please try after uninstalling `aria2c` or try another downloader with `-d` option. For example if you got `curl` installed then `-d curl`.

**Comment by Brunaldo** [comment]
I uninstalled aria2 using `brew remove aria2` , then reinstalled manually using  `https://github.com/aria2/aria2/releases/tag/release-1.25.0` (the dmg) and that didn't work either Reinstalled aria2 using `brew install aria2` and it still doesn't work.

It's strange, it downloads the first 2 videos in folder 1 and crashes.

**Comment by nishad** [comment]
Could you try with 

-d curl

**Comment by Brunaldo** [comment]
I don't understand what you mean. Can you please give me an example as to what commands I would enter. I've installed curl using `brew install curl`.

Thanks.

**Comment by ashimloves** [comment]
I have the same problem for same course o.O. Removed and used curl as well, same issue persist.
Downloading attached files

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file .\attached_files\014 Security
Warning: Vulnerabilities Threats and
Warning: Adversaries\The-Cyber-Security-Landscape-Diagram.jpg.tmp: No such
Warning: file or directory
  0  777k    0  1129    0     0   1477      0  0:08:58 --:--:--  0:08:58  1477
curl: (23) Failed writing body (0 != 1129)
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 886, in <module>
  File "<string>", line 883, in main
  File "<string>", line 742, in udemy_dl
  File "<string>", line 660, in get_data
  File "<string>", line 559, in get_attached_file
  File "<string>", line 620, in check_downloaded
WindowsError: [Error 3] The system cannot find the path specified
None
udemy_dl returned -1

**Comment by ashimloves** [comment]
What i did as a workaround is to save the links to a file and then used wget -i filename
I had to create the folder structure manually of-course but I am fine with that ...

**Comment by egadgetjnr** [comment]
@ashimloves Could you do a `--debug` on the course you were working on when you got the error and also the `--save-links` file you mentioned for comparison?
This will allow us to have a look at what data it is getting in terms of path in the API response and what you're getting in the `--save-links` file.

**Comment by ashimloves** [comment]
Sorry buddy, I had some difficulties with course in Udemy app as well, so I got a refund, and now don't have access to that course now. Next time if I face that issue, I will do it in debug mode.
And yes, apparently there is some issue with the 3rd video in the --save-links option as well. But from the website it can be played without any issue.

**Comment by soamz** [comment]
Same issue, not able to download past 5 chapters. :(

**Comment by 1geeky** [comment]
> @nishad commented on Jul 25, 2016
>
> Could you try with
> -d curl

the `-d curl` solved my problem. I think the issue may be with the default download directory which is set in the `~/.aria2/aria2.conf`.
In my case, it was `dir=Downloads` and so the script would downloaded **tmp** files inside an extra `/Downloads` folder nested in the for example chapter 01 folder. Therefore it encountered error while looking for the **tmp** file to rename. At the correct situation (e.g while using `curl`),  **tmp** file should be in the root of a course chapter not in `chapter01/Downloads/video.mp4.tmp`

**Comment by find4u** [comment]
[debug_udemy-dl.zip](https://github.com/nishad/udemy-dl/files/704247/debug_udemy-dl.zip)

Hi I have the same or very similar problem. Your wonderfull script has worked fine on other courses I have attached the debug dir. 

Thanks for creating

Richard

**Comment by find4u** [comment]
using --safe-file-names cured the problemhope this helps someone else thanks a million

Richard

**Comment by find4u** [comment]
I tried safe filenames that did not work so I just set the --lecture-start to the lecture after the one that failed and got the rest of the course. so only one lecture would not work. Hope this help someone else.
