### ISSUE TITLE
Partial download

### ISSUE THREAD

**Issue by vanatomas** [nishad/udemy-dl#13]
I was able partially download course, but I got error that stop processing rest of lectures

Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 220, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 161, in udemy_dl
    get_video(directory, filename, video['video_url'])
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 137, in get_video
    download(link, filename)
  File "/Library/Python/2.7/site-packages/udemy_dl/download.py", line 11, in download
    if 'youtube.com' in link:
TypeError: argument of type 'NoneType' is not iterable

Any hints?

**Comment by mukhlesur-millon** [comment]
it was fixed here
 Download crash after a while #12

**Comment by vanatomas** [comment]
thank you, it works now
