### ISSUE TITLE
TypeError: 'NoneType' object has no attribute 'getitem'

### ISSUE THREAD

**Issue by hxor** [nishad/udemy-dl#132]
I got some error like this

Downloading attached files
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 706, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 624, in get_data
    get_attached_file(file_dir, attached_info)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 523, in get_attached_file
    for element in attached_json['download_urls']['File']:
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by egadgetjnr** [comment]
You might need to check before wasting time posting this.
1. You need to complete the mandatory checklist before @nishad will even look at this.
2. If you had have read the mandatory checklist, you will search and find that this has already been raised in #125 and has a work around in place 

> `sudo pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master`

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
