### ISSUE TITLE
[BUG] Found course id: logo.jpg

### ISSUE THREAD

**Issue by 7ang** [nishad/udemy-dl#141]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{[INFO-107] Trying to log in ...
[INFO-137] Login success.
[INFO-169] Found course id: logo.jpg
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 666, in udemy_dl
    for data in get_data_links(course_id, lecture_start, lecture_end):
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 359, in get_data_links
    course_data_len = len(course_data['results'])
KeyError: u'results'}

**Comment by egadgetjnr** [comment]
Can you post the command you're running? What's the course URL?

**Comment by 7ang** [comment]
https://www.udemy.com/react-flux/
CML: udemy-dl https://www.udemy.com/react-flux/

That ’s it

**Comment by Runjesh** [comment]
Getting Same Error,It Downloads First Two Chapters than this error comes

runjeshs-MacBook-Pro:~ runjesh$ udemy-dl -u xxxxx@gmail.com -p AAFAFAFQFVA -q 54321  https://www.udemy.com/an-entire-mba-in-1-courseaward-winning-business-school-prof

**Comment by tobias-p** [comment]
maybe you guys should try to the complete url... 

a course of mine has following url: https://www.udemy.com/javafx-gui/learn/v4

Try to add "/learn/v4" to your urls and then try again to download the course.

**Comment by AlexVentura** [comment]
Hi there!
I have the same problem with payed courses but not with free ones. I'm doing this:
````
udemy-dl https://www.udemy.com/javafx-gui/
Username / Email : hmc@infinitummail.com
Password :
[INFO-927] Downloading to: /Users/alex/javafx-gui

[INFO-132] Trying to log in ...
[INFO-161] Login success.
[INFO-193] Found course id: 495990
[INFO-205] Found course title: JavaFX 8 - Der Einstieg in die Java-GUI Programmierung
[ERROR-60] Exception
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 930, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 746, in udemy_dl
    for data in get_data_links(course_id, lecture_start, lecture_end):
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 392, in get_data_links
    course_data_len = len(course_data['results'])
KeyError: u'results'
````
I'm on `macOS Sierr`, `Python 2.7.10`, `udemy-dl 0.2.2-alpha`

Any suggest?

**Comment by tobias-p** [comment]
Alex, please read the last post of mine... also i am wondering, why you guys dont use python 3.5.x instead of python 2.7.x.... ^^

**Comment by AlexVentura** [comment]
@tobias-p Thanks for your support!

Now I'm in Ubuntu Desktop 16.04 and by default there are two different Python versions:

running: `python --version` returns:
````
Python 2.7.11+
````

running: `python3 --version` returns:
````
Python 3.5.1+
````

> So  I started to use Python 3:

- Iinstall pip, I typed:
`sudo curl https://bootstrap.pypa.io/get-pip.py | sudo python3`

_...everything seemed to be fine..._

- Installing udemy-dl:
`python3 -m pip install udemy-dl`

_...everything seemed to be fine..._

- Verify *udemy-dl* version:
`udemy-dl --version`  I got:
````
udemy-dl 0.2.1
````
- Using udemy-dl:
`python3 -m udemy_dl https://www.udemy.com/realtime-apps-with-reactjs-golang-rethinkdb`
and I got:
````
Username / Email : me@you.com
Password : 
[INFO-835] Downloading to: /home/alex/realtime-apps-with-reactjs-golang-rethinkdb

[INFO-107] Trying to log in ...
[INFO-137] Login success.
[INFO-169] Found course id: 745306
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/udemy_dl/__main__.py", line 8, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/local/lib/python3.5/dist-packages/udemy_dl/udemy_dl.py", line 666, in udemy_dl
    for data in get_data_links(course_id, lecture_start, lecture_end):
  File "/usr/local/lib/python3.5/dist-packages/udemy_dl/udemy_dl.py", line 359, in get_data_links
    course_data_len = len(course_data['results'])
KeyError: 'results'
````

So what I did wrong?
Thanks in advance! 😄

**Comment by tobias-p** [comment]
You did the following wrong: you updated to latest normal version ^^ Check out the wiki here to update to the latest developer version :P

**Comment by TimMeade** [comment]
Running latest developer version.  Centos 7 python 3.5.   No matter what I try i get Found course id: logo.jpg  then this error.

**Comment by TimMeade** [comment]
Update to this:    I rewrote to see what is coming back when the course is grabbed:

{ error: 'Please accept our latest Terms of Service.' }

**Comment by arush-sal** [comment]
This error occurs if you aren't enrolled in the course. Do enroll in the course first then try to download it.

**Comment by TimMeade** [comment]
This is a paid course.    So pretty sure i was enrolled.

**Comment by arush-sal** [comment]
Well, I was facing the same issue earlier I enrolled in the course. Once I did its downloading fine.

**Comment by montera82** [comment]
I faced this issue because i did not enroll into the cource yet before attempting to download.
