### ISSUE TITLE
[ERROR-60] -- Uncompleted download process 

### ISSUE THREAD

**Issue by SKYLOR7** [nishad/udemy-dl#152]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked that the issue I'm posting isn't already reported.
- [x ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [x ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

The project worked fine and did download everything temporary but this error came up. As a result there aren't any completed videos except 2 out of 56!! 

> Status Legend:
> (OK):download completed.

> [ERROR-60] Exception
> Traceback (most recent call last):
>   File "/usr/local/bin/udemy-dl", line 7, in <module>
>     main()
>   File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 930, in main
>     save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
>   File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 786, in udemy_dl
>     get_data(directory, filename, data_url, data_type, attached_info, caption_list)
>   File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 667, in get_data
>     html_json = session.get(link).json()
>   File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 90, in get
>     return self.session.get(url, headers=self.headers)
>   File "/Library/Python/2.7/site-packages/requests/sessions.py", line 488, in get
>     return self.request('GET', url, **kwargs)
>   File "/Library/Python/2.7/site-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Library/Python/2.7/site-packages/requests/sessions.py", line 596, in send
>     r = adapter.send(request, **kwargs)
>   File "/Library/Python/2.7/site-packages/requests/adapters.py", line 473, in send
>     raise ConnectionError(err, request=request)
> ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))
> 

Any thoughts ??

**Comment by jaan143** [comment]
@SKYLOR7 your also faced "Critical 47" error and now its solved in your side ? you can download any course now ?

**Comment by nishad** [comment]
@SKYLOR7, please verify your version number, `v0.2.2`is not yet released.
