### ISSUE TITLE
[BUG]:  [CRITICAL-407] Cannot download lecture "blah....": "'NoneType' object has no attribute 'group'"

### ISSUE THREAD

**Issue by yahxaris** [nishad/udemy-dl#160]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **udemy-dl 0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

When trying to pull, list, save links, or debug for java-the-complete-java-developer-course I get the following error over and over for each lecture 

[CRITICAL-407] Cannot download lecture "Method Overloading": "'NoneType' object has no attribute 'group'"

One thing to note, this occurs when I run it with python in Cygwin, but I do not see the problem with the Windows version.

$ udemy-dl -s -u <email> -p <password> https://www.udemy.com/java-the-complete-java-developer-course --debug
[DEBUG-792] Debug mode is enabled, debug files will be saved in :
/home/python/nishad-udemy-dl-v0.2.1-33-g4c01eeb.tar/nishad-udemy-dl-v0.2.1-33-g4c01eeb/nishad-udemy-dl-4c01eeb/src/udemy_dl

[INFO-833] Saving links to: /home/python/nishad-udemy-dl-v0.2.1-33-g4c01eeb.tar/nishad-udemy-dl-v0.2.1-33-g4c01eeb/nishad-udemy-dl-4c01eeb/src/udemy_dl/java-the-complete-java-developer-course.txt

[INFO-107] Trying to log in ...
[INFO-137] Login success.
[DEBUG-157] Searching course id...
[INFO-169] Found course id: 533682
....
[CRITICAL-407] Cannot download lecture "Inheritance - Part 2": "'NoneType' object has no attribute 'group'"
Getting course data: 20.66% [====----------------] [DEBUG-181] Saving json source: 3303886
[DEBUG-224] Found list_m3u8
Traceback (most recent call last):
  File "/usr/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 666, in udemy_dl
    for data in get_data_links(course_id, lecture_start, lecture_end):
  File "/usr/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 377, in get_data_links
    data_url, data_type, caption_list = extract_lecture_url(course_id, lecture_id, item['asset']['asset_type'])
  File "/usr/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 186, in extract_lecture_url
    return parse_video(json_source)
  File "/usr/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 226, in parse_video
    m3u8_str = requests.get(link).text
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 267, in ssl_wrap_socket
    context.load_verify_locations(ca_certs)
KeyboardInterrupt

**Comment by nishad** [comment]
You can try with the latest development version `0.2.2-alpha`. This issue is addressed long back.
