### ISSUE TITLE
[BUG] - Crashed during downloading

### ISSUE THREAD

**Issue by karek314** [nishad/udemy-dl#170]
During downloading content udemy-dl crashed with following error
```
[ERROR-60] Exception
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 930, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 786, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 683, in get_data
    get_caption(file_dir, caption_list)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 529, in get_caption
    caption = requests.get(link).text
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
```

Version 2.2 alpha

**Comment by TechTreeDev** [comment]
I got the same error

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Comment by karek314** [comment]
I don't care as much to fill those stupid checkboxes, but since i've already reported, here we go

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.
