### ISSUE TITLE
[BUG] - Error 60 Exception

### ISSUE THREAD

**Issue by karek314** [nishad/udemy-dl#171]
While downloading captions udem-dl crashed with unhandled exception

Downloading captions

```
[ERROR-60] Exception
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 930, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 786, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 641, in get_data
    print('\n\nDownloading {0}: {1!s}\n'.format(data_type, filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 42: ordinal not in range(128)
```

**Comment by karek314** [comment]
It appears that video name contains character "é" which caused exception. I think it should use UTF8 instead ASCII, anyway i've successfully downloaded content by switching to `--safe-file-names`
