### ISSUE TITLE
[BUG] 'ascii' codec can't decode byte 0xc3 in position 361

### ISSUE THREAD

**Issue by Kcchouette** [nishad/udemy-dl#179]
Version : **X.X.X** latest, installation using pip and python3.

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [x] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

```
# pip3 install udemy-dl
Collecting udemy-dl
  Using cached udemy-dl-0.2.1.tar.gz
Collecting requests (from udemy-dl)
  Using cached requests-2.12.4-py2.py3-none-any.whl
Collecting unicode-slugify (from udemy-dl)
  Using cached unicode-slugify-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zcrv9ujg/unicode-slugify/setup.py", line 7, in <module>
        long_description=open('README.md').read(),
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 361: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zcrv9ujg/unicode-slugify/
```

**Comment by rustanacexd** [comment]
seems an issue with unicode_slugify package
