### ISSUE TITLE
[BUG] Downloading attachments failing

### ISSUE THREAD

**Issue by byrash** [nishad/udemy-dl#192]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ X ] I have checked that the issue I'm posting isn't already reported.
- [ X ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ X ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ X ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

I have been observing for a particular course (python-step-by-step-build-a-data-analysis-program) downloading attachments keeps failing always with exception below

Status Legend:
(OK):download completed.

Downloading attached files
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 706, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 624, in get_data
    get_attached_file(file_dir, attached_info)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 523, in get_attached_file
    for element in attached_json['download_urls']['File']:
KeyError: u'File'

I have to use --lecture-start to start from next lecture after where it failed to download.

Can this be resolved ?

PS: As a side note ( please correct if i missed some option ), would it be good if I can ask the program to skip downloading attachments ?

**Comment by nishad** [comment]
I will investigate this issue. However you can open a separate proposal as well for 'skipping attachments'.

**Comment by byrash** [comment]
Will do. Cheers

**Comment by byrash** [comment]
A small lead to solve this defect, have been observing this pattern if a download artefact is a html file. For that matter, it was downloading the html file (may be affecting attachments too) but failing after that.

**Comment by byrash** [comment]
After failing with resource download have to start from next section using --lecture-start option.
