### ISSUE TITLE
failed to install udemy-dl linux mint

### ISSUE THREAD

**Issue by AbhimanyuAryan** [nishad/udemy-dl#196]
I get this error when trying to install udemy-dl 

```
python -m pip install udemy-dl
Collecting udemy-dl
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from udemy-dl)
Collecting future (from udemy-dl)
Collecting colorlog (from udemy-dl)
  Using cached colorlog-2.10.0-py2.py3-none-any.whl
Collecting unicode-slugify (from udemy-dl)
Collecting unidecode (from unicode-slugify->udemy-dl)
  Using cached Unidecode-0.04.20-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from unicode-slugify->udemy-dl)
Installing collected packages: future, colorlog, unidecode, unicode-slugify, udemy-dl
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/libfuturize'

```

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
