### ISSUE TITLE
[BUG] Course fails to download: “KeyError: u'results'”

### ISSUE THREAD

**Issue by benf-wspdigital** [nishad/udemy-dl#201]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

When attempting to retrieve the course https://www.udemy.com/storytellingtoinfluence/ I get the following output:

> $ python2 -m udemy_dl https://www.udemy.com/storytellingtoinfluence/
> Username / Email : ben.finney@wspeonline.com
> Password : 
> [INFO-835] Downloading to: /Users/benfinney/Videos/Udemy/Storytelling to Influence/storytellingtoinfluence
> 
> [INFO-107] Trying to log in ...
> [INFO-137] Login success.
> [INFO-169] Found course id: 941752
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/Users/benfinney/Library/Python/2.7/lib/python/site-packages/udemy_dl/__main__.py", line 8, in <module>
>     main()
>   File "/Users/benfinney/Library/Python/2.7/lib/python/site-packages/udemy_dl/udemy_dl.py", line 837, in main
>     udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
>   File "/Users/benfinney/Library/Python/2.7/lib/python/site-packages/udemy_dl/udemy_dl.py", line 666, in udemy_dl
>     for data in get_data_links(course_id, lecture_start, lecture_end):
>   File "/Users/benfinney/Library/Python/2.7/lib/python/site-packages/udemy_dl/udemy_dl.py", line 359, in get_data_links
>     course_data_len = len(course_data['results'])
> KeyError: u'results'

**Comment by benf-wspdigital** [comment]
This behaviour happens for me only when I attempt to download a course for which I am not yet enrolled.

When I have already enrolled in a course, the same command downloads the course material successfully.

I expect that ‘udemy_dl’ is receiving some message that the course material is not available. So, that should be displayed to the user as a more comprehensible error message, not a Python stack trace.

**Comment by mhaselup** [comment]
I am experiencing a similar/the same problem on Mac OS X 10.12.1

In my case the error occurs when downloading a course which I AM enrolled in. Output is below:

users-MacBook-Pro:src user$ sudo udemy-dl https://www.udemy.com/LearnandUnderstandAngularJS/
Username / Email : xxxxxxxxx
Password : 
[INFO-835] Downloading to: /Users/user/Downloads/udemy-dl-master/src/LearnandUnderstandAngularJS

[INFO-107] Trying to log in ...
[INFO-137] Login success.
[INFO-169] Found course id: logo.jpg
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 666, in udemy_dl
    for data in get_data_links(course_id, lecture_start, lecture_end):
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 359, in get_data_links
    course_data_len = len(course_data['results'])
KeyError: u'results'
users-MacBook-Pro:src user$
