### ISSUE TITLE
[BUG] KeyError: 'File' while trying to download .py attached files

### ISSUE THREAD

**Issue by damnko** [nishad/udemy-dl#202]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

The download fails each time it tries to download a `.py` file, this is the traceback:
```
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/local/lib/python3.6/site-packages/udemy_dl/udemy_dl.py", line 706, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/usr/local/lib/python3.6/site-packages/udemy_dl/udemy_dl.py", line 624, in get_data
    get_attached_file(file_dir, attached_info)
  File "/usr/local/lib/python3.6/site-packages/udemy_dl/udemy_dl.py", line 523, in get_attached_file
    for element in attached_json['download_urls']['File']:
KeyError: 'File'
```
As per @byrash suggestion, it would be nice to be able to skip attachments download.

**Comment by carlos-esteves** [comment]
The download fails each time it tries to download a .py file, this is the traceback:
Downloading: 100.00% [==============================] Done
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/udemy_dl/__main__.py", line 8, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 706, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 624, in get_data
    get_attached_file(file_dir, attached_info)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 523, in get_attached_file
    for element in attached_json['download_urls']['File']:
KeyError: u'File'
