### ISSUE TITLE
[BUG] Could not download

### ISSUE THREAD

**Issue by ankit191188** [nishad/udemy-dl#203]
C:\Users\pandanki\Desktop\Udemy\udemy-dl-win>udemy-dl.exe https://www.udemy.com/
javafx-gui/learn/v4/overview --use-ffmpeg
Username / Email : xxxxxxxx@xxxx.com
Password :
[INFO-884] Downloading to: C:\Users\pandanki\Desktop\Udemy\udemy-dl-win\javafx-g
ui

[INFO-127] Trying to log in ...
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 697, in udemy_dl
  File "<string>", line 129, in login
  File "<string>", line 115, in get_csrf_token
  File "<string>", line 85, in get
  File "site-packages\requests\sessions.py", line 480, in get
  File "site-packages\requests\sessions.py", line 468, in request
  File "site-packages\requests\sessions.py", line 576, in send
  File "site-packages\requests\adapters.py", line 437, in send
ConnectionError: HTTPSConnectionPool(host='www.udemy.com', port=443): Max retrie
s exceeded with url: /join/login-popup (Caused by NewConnectionError('<requests.
packages.urllib3.connection.VerifiedHTTPSConnection object at 0x02C68990>: Faile
d to establish a new connection: [Errno 10060] A connection attempt failed becau
se the connected party did not properly respond after a period of time, or estab
lished connection failed because connected host has failed to respond',))
None
udemy_dl returned -1

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
