### ISSUE TITLE
[BUG]Crash with french characters in name file ou title

### ISSUE THREAD

**Issue by benoitdurand** [nishad/udemy-dl#215]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.2-alpha**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [X] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
Hi,

I want to download french udemy formations, but udemy-dl crash with french characters :

[INFO-133] Trying to log in ...
[INFO-162] Login success.
[INFO-194] Found course id: 1011114
[INFO-206] Found course title: Hacking **É**thique : Le Cours Complet
Getting course data: 100.00% [====================] Done
[ERROR-61] Exception
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 947, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 803, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 658, in get_data
    print('\n\nDownloading {0}: {1!s}\n'.format(data_type, filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 27: ordinal not in range(128)

Work's fine for others formations.

**Comment by nishad** [comment]
Could you please try with `--safe-file-names` and post the result ?

**Comment by benoitdurand** [comment]
Work's fine with --safe-file-name

**Comment by briviza** [comment]
Could you pl. explain more on how to try --safe-file-names ? As it seems I have similar issue with Japanese characters in file name so the file can't be encoded and downloaded. 
Thank you.
