### ISSUE TITLE
Exception: Failed to execute script udemy_dl

### ISSUE THREAD

**Issue by Bhuyang** [nishad/udemy-dl#237]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

I got below listed error while downloading the course. Please do needful. 

2017-07-29 01:08:14,394 - [DEBUG-urllib3.connectionpool-395] - https://www.udemy.com:443 "GET /api-2.0/users/me/subscribed-courses/696050/lectures/6164632?fields[asset]=@min,download_urls,external_url,slide_urls&fields[course]=id,is_paid,url&fields[lecture]=@default,view_html,course&page_config=ct_v4 HTTP/1.1" 200 None
2017-07-29 01:08:14,697 - [DEBUG-urllib3.connectionpool-395] - https://www.udemy.com:443 "GET /api-2.0/users/me/subscribed-courses/696050/lectures/6164632/supplementary-assets/7340098?fields[asset]=download_urls HTTP/1.1" 200 None
2017-07-29 01:08:17,984 - [ERROR-__main__-83] - Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 825, in udemy_dl
  File "udemy_dl.py", line 718, in get_data
  File "udemy_dl.py", line 612, in get_attached_file
  File "udemy_dl.py", line 675, in check_downloaded
WindowsError: [Error 3] The system cannot find the path specified

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **2.1.3*

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here, replace this line with your issue content}

**Comment by RISHITSONECHA** [comment]
It'll work only if you've enrolled in that course. This script won't download paid courses for free.If you've already enrolled and yet you've a problem try to run 
update.cmd 
and than try again

**Comment by Puyodead1** [comment]
same problem, any fix?

**Comment by Puyodead1** [comment]
@RISHITSONECHA its update.bat btw and i have run it

**Comment by Puyodead1** [comment]
FIXED IT, unzip the udemy-dl zip to a differant folder, update it, and try
