### ISSUE TITLE
[QUESTION] Can't proceed to login

### ISSUE THREAD

**Issue by melgomez** [nishad/udemy-dl#258]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Good day!

I have used udemy-dl a couple of months ago and was running smoothly on my mac. I'm just bothered that it has somehow returning bunches of error. Maybe some of you guys can shed light on these errors.

Log:
>[INFO-107] Trying to log in ...
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 658, in udemy_dl
    login(username, password)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 109, in login
    csrf_token = get_csrf_token()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 95, in get_csrf_token
    response = session.get('https://www.udemy.com/join/login-popup')
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 66, in get
    return self.session.get(url, headers=self.headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.udemy.com', port=443): Max retries exceeded with url: /join/login-popup (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))

I also have tried upgrading it but somehow a certain package is deprecated and i don't know if it could have affected the whole thing. 

Log:
>Requirement already up-to-date: udemy-dl in /Library/Python/2.7/site-packages
Requirement already up-to-date: requests in /Library/Python/2.7/site-packages (from udemy-dl)
Requirement already up-to-date: unicode-slugify in /Library/Python/2.7/site-packages (from udemy-dl)
Requirement already up-to-date: colorlog in /Library/Python/2.7/site-packages (from udemy-dl)
Requirement already up-to-date: future in /Library/Python/2.7/site-packages (from udemy-dl)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /Library/Python/2.7/site-packages (from requests->udemy-dl)
Requirement already up-to-date: idna<2.7,>=2.5 in /Library/Python/2.7/site-packages (from requests->udemy-dl)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests->udemy-dl)
Requirement already up-to-date: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests->udemy-dl)
Collecting six (from unicode-slugify->udemy-dl)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting unidecode (from unicode-slugify->udemy-dl)
  Using cached Unidecode-0.04.21-py2.py3-none-any.whl
Installing collected packages: six, unidecode
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/xm/jb6jp2zd1g35ql87j9wswf580000gn/T/pip-lLtpJt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by shoumma** [comment]
Facing the same issue. Something might to do with HTTPS call.

**Comment by voleoo** [comment]
@melgomez  @shoumma   `sudo pip install --upgrade pyOpenSSL`

**Comment by melgomez** [comment]
@voleoo tried your solution however it doesn't properly install or upgrades pyOpenSSL, instead it uninstalls it in the end due to depracation. Thanks by the way!

End Log:

>Found` existing installation: pyOpenSSL 0.13.1
    DEPRECATION: Uninstalling a distutils installed project (pyOpenSSL) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pyOpenSSL-0.13.1:
      Successfully uninstalled pyOpenSSL-0.13.1

**Comment by timeff** [comment]
I've tried this and it works well :)

`pip install --user  --upgrade pyOpenSSL`

**Comment by KyleFromOhio** [comment]
If you get DEPRECATED errors about six or other packages included with OSX try...
`sudo -H pip install --ignore-installed pyOpenSSL`

**Comment by X-R0** [comment]
still facing this issue,

this is my last log:

> [INFO-133] Trying to log in ...
[ERROR-61] Exception
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/udemy_dl/__main__.py", line 8, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 947, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 744, in udemy_dl
    login(username, password)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 134, in login
    csrf_token = get_csrf_token()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 121, in get_csrf_token
    response = session.get(LOGIN_POPUP_URL)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 91, in get
    return self.session.get(url, headers=self.headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='www.udemy.com', port=443): Max retries exceeded with url: /join/login-popup (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))

py0penSSL already up-to-date.

I see _SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)_
seems like a SSL protocol issue. Any further ideas how to fix this on OS-X?

thank you

**Comment by X-R0** [comment]
_update:_

ssl issue only on os-x.

I checked it on a linux device and it works fine, but it just downloaded the additional html files... not the course itself.
Any clue why?

**Comment by SmartTechie** [comment]
getting same ssl issue on os-x

**Comment by calvyntwh** [comment]
works now with the solution from @KyleFromOhio, i am on os-x

**Comment by X-R0** [comment]
I ignore the py0penssl like @KyleFromOhio suggest, but still facing the same issue on OSX

`[INFO-107] Trying to log in ...
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/udemy_dl/__main__.py", line 8, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 658, in udemy_dl
    login(username, password)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 109, in login
    csrf_token = get_csrf_token()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 95, in get_csrf_token
    response = session.get('https://www.udemy.com/join/login-popup')
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 66, in get
    return self.session.get(url, headers=self.headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.udemy.com', port=443): Max retries exceeded with url: /join/login-popup (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))`

still ssl errors

**Comment by himak** [comment]
@KyleFromOhio thx its help me.

**Comment by azizultex** [comment]
Thanks @KyleFromOhio
