### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by mujdatkilic** [nishad/udemy-dl#259]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked that the issue I'm posting isn't already reported.
- [ x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{hello, 
Downloading attached files

 UnicodeEncodeError encountered using external_downloader -- Trying internal
 Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 825, in udemy_dl
  File "udemy_dl.py", line 718, in get_data
  File "udemy_dl.py", line 612, in get_attached_file
  File "udemy_dl.py", line 673, in check_downloaded
  File "download.py", line 54, in download
  File "download.py", line 128, in requests_dl
IOError: [Errno 2] No such file or directory: u'.\\attached_files\\009 Sublime Text Edit\xf6r Kurulumu ve Yap\u0131land\u0131rma Ayarlar\u0131\\Sublime-Text-Build-3126-x64-Setup.exe.tmp'
Failed to execute script udemy_dl

what is the problem}

**Comment by mujdatkilic** [comment]
I solved the problem.
for solution
https://support.microsoft.com/en-us/help/982502/you-cannot-back-up-a-file-in-windows-server-2008-r2-or-in-windows-7-if?utm_campaign=DonanimHaber&utm_medium=referral&utm_source=DonanimHaber
