### ISSUE TITLE
[BUG] Error when downloading paid udemy course

### ISSUE THREAD

**Issue by gauravsoni1** [nishad/udemy-dl#260]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **udemy-dl 0.2.2-alpha.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Udemy-dl was working before , now it gives me an error

After proceeding with entering the username and password I get the following error

`[INFO-133] Trying to log in ...
[ERROR-61] Exception
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 948, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 745, in udemy_dl
    login(username, password)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 134, in login
    csrf_token = get_csrf_token()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 121, in get_csrf_token
    response = session.get(LOGIN_POPUP_URL)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 91, in get
    return self.session.get(url, headers=self.headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='www.udemy.com', port=443): Max retries exceeded with url: /join/login-popup (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))`

**Comment by rmit-s3583574-siqi-yang** [comment]
I got the same error

**Comment by vijaythecoder** [comment]
same here

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Comment by gauravsoni1** [comment]
@nishad Updated the questions , please reopen

**Comment by 123gkc** [comment]
Same issue.

**Comment by swarupsro** [comment]
same problem found ..
[CRITICAL-238] Skipped. Expected quality not found!

**Comment by vijay-js** [comment]
same issue for me too. Any resolution @nishad ?

**Comment by UTNLuciano** [comment]
@swarupsro 
 try uninstalling first with pip uninstall udemy-dl then
reinstall with sudo pip install udemy-dl==0.2.2-alpha.2

thanks to @wunderkid

**Comment by davidhenley** [comment]
Tried above did not work.

This used to work fine as little as a week ago. Now something is wrong. Nothing has changed.

**Comment by devenvyas** [comment]
@davidhenley This is what worked for me:
The issue is with the current python using TLS v1.0 whereas Udemy demands v1.2

Check which TLS is being used with
```
$ python2 -c "import json, urllib2; print json.load(urllib2.urlopen('https://www.howsmyssl.com/a/check'))['tls_version']"
```
If it is TLS v1.0 then it can be fixed as follows:

1. Upgrade python2 to 2.7.14
```
$ brew install python2
```
2. Make sure virtualenv is using the latest python
```
$ virtualenv --python=/usr/local/bin/python2 venv
```

**Comment by roshangm1** [comment]
@devenvyas not working still.

**Comment by vijaythecoder** [comment]
one of the answers from other thread worked for me. https://github.com/nishad/udemy-dl/issues/258 @roshangm1

**Comment by roshangm1** [comment]
Great. The answer there solved my issue. Thanks @vijaythecoder

**Comment by gauravsoni1** [comment]
@vijaythecoder Thanks , it worked.

For reference, use `sudo pip install --upgrade pyOpenSSL`

For people get deprecation error user `sudo -H pip install --ignore-installed pyOpenSS`

**Comment by nikunjjoshi** [comment]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/udemy_dl/__main__.py", line 8, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/udemy_dl/udemy_dl.py", line 666, in udemy_dl
    for data in get_data_links(course_id, lecture_start, lecture_end):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/udemy_dl/udemy_dl.py", line 359, in get_data_links
    course_data_len = len(course_data['results'])
KeyError: 'results'

help plz...

**Comment by davidhenley** [comment]
Still not working after trying all above...

```
[INFO-133] Trying to log in ...
[ERROR-61] Exception
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 947, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 744, in udemy_dl
    login(username, password)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 134, in login
    csrf_token = get_csrf_token()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 121, in get_csrf_token
    response = session.get(LOGIN_POPUP_URL)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 91, in get
    return self.session.get(url, headers=self.headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='www.udemy.com', port=443): Max retries exceeded with url: /join/login-popup (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))
```
