### ISSUE TITLE
This is the error i get

### ISSUE THREAD

**Issue by preciousokwu** [nishad/udemy-dl#262]
> [INFO-133] Trying to log in ...
[INFO-162] Login success.
[INFO-194] Found course id: 438522
[INFO-206] Found course title: Learn 3D Modelling - The Complete Blender Creator Course
[ERROR-61] Exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/__main__.py", line 8, in <module>

**Comment by joshpitzalis** [comment]
+1

**Comment by nikunjjoshi** [comment]
[ERROR-61] Exception
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 947, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 763, in udemy_dl
    for data in get_data_links(course_id, lecture_start, lecture_end):
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 409, in get_data_links
    course_data_len = len(course_data['results'])
KeyError: u'results'
