### ISSUE TITLE
Bug Failed to execute script udemy_dl

### ISSUE THREAD

**Issue by gh05twr1t3r** [nishad/udemy-dl#264]
Downloading to: C:\Users\User\Downloads\udemy-dl-windows-2.1.3\udemy-dl-windows\javafx-gui

 Trying to log in ...
 Login success.
 Found course id: 495990
 Found course title: JavaFX 8 - Der Einstieg in die Java-GUI Programmierung
 Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 785, in udemy_dl
  File "udemy_dl.py", line 431, in get_data_links
KeyError: u'results'
Failed to execute script udemy_dl

**Comment by ppagan** [comment]
This has happened to me before on Fedora 26 using 0.2.2-alpha.2 - I went so far as to edit the python code to dump the contents of variables to screen right before this error occured and found that instead of an object being populated with a list of results for videos to download, it was simply getting a string of "not authorized". That's what causing the KeyError - there is no key called 'results' being returned.

The strange thing is that somehow, eventually, after trying over and over again in the process of trying to debug the issue, the download worked. Keep trying, see if it works for you eventually, and let us know. We are not the only people to have had this problem.
