### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by rainmanjam** [nishad/udemy-dl#29]
```
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 289, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir, save_links)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 219, in udemy_dl
    filename = '{0:03d} {1!s}.mp4'.format(video['lecture_number'], video['lecture'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 27: ordinal not in range(128)
```

**Comment by mukhlesur-millon** [comment]
upgrade it

**Comment by rainmanjam** [comment]
I'm using 0.2.0 with Python 2.8

**Comment by nishad** [comment]
https://github.com/nishad/udemy-dl/wiki/Installing-development-version
