### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by mucahiddanis** [nishad/udemy-dl#31]
```
Traceback (most recent call last):
  File "<string>", line 288, in <module>
  File "<string>", line 284, in main
  File "<string>", line 215, in udemy_dl
  File "<string>", line 172, in get_video_links
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\encodings.cp857", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2026' in position 80: character maps to <undefined>
```

I can't download udemy video.  (Python 2.7 installed)
![error](https://cloud.githubusercontent.com/assets/16820194/12531067/cd73189e-c1fa-11e5-9b36-41b17de702d4.png)

**Comment by mukhlesur-millon** [comment]
upgrade it...
``python -m pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master``

**Comment by mucahiddanis** [comment]
unfortunately it did not work

**Comment by nishad** [comment]
This error got nothing to do with this project
