### ISSUE TITLE
Download fails when lecture name contains unusual letters

### ISSUE THREAD

**Issue by ChristianAE** [nishad/udemy-dl#41]
Trying to download a course with the name "Lecture 20: Façade pattern" fails with the following error.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/.local/lib/python2.7/site-packages/udemy_dl/__main__.py", line 5, in <module>
    main()
  File "/home/user/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 289, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir, save_links)
  File "/home/user/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 219, in udemy_dl
    filename = '{0:03d} {1!s}.mp4'.format(video['lecture_number'], video['lecture'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 2: ordinal not in range(128)
```

**Comment by ksdsksd** [comment]
I had the same problem.
I fixed it by adding the following into lib/python2.7/site-packages/udemy_dl/udemy_dl.py 
after the line:     lecture = item['title']

            temp = ""
            for char in lecture:
                if ord(char) < 128:
                    temp += char
            lecture = temp

**Comment by ChristianAE** [comment]
I am not familiar with Python/pip. How do I get the latest development version? _pip install --upgrade udemy-dl_ downloads 0.2.0.

**Comment by mukhlesur-millon** [comment]
https://github.com/nishad/udemy-dl/wiki/Installing-development-version @ChristianAE

**Comment by ChristianAE** [comment]
I get the same error now on a different lecture as well. The name of the lecture is _Lecture 19: Introduction_. 

Jumping directly to the originally failed lecture using _--lecture-start_ results in the same error.

Can I provide more information to pin-point the cause of the error?

```
Downloading Video: 019 Introduction
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.4M  100 13.4M    0     0   737k      0  0:00:18  0:00:18 --:--:--  971k
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/.local/lib/python2.7/site-packages/udemy_dl/__main__.py", line 8, in <module>
    main()
  File "/home/user/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 551, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/home/user/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 437, in udemy_dl
    filename = '{0:03d} {1!s}.mp4'.format(data['lecture_number'], safeencode(data['lecture']))
  File "/home/user/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 62, in safeencode
    return str(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 2: ordinal not in range(128)

```

**Comment by mukhlesur-millon** [comment]
test this one @ChristianAE 
`python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master`

**Comment by ChristianAE** [comment]
That one works.
