### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by hx0a1q** [nishad/udemy-dl#58]
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 289, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir, save_links)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 219, in udemy_dl
    filename = '{0:03d} {1!s}.mp4'.format(video['lecture_number'], video['lecture'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 12: ordinal not in range(128)

**Comment by nishad** [comment]
This repository requires mandatory check lists for all issues. Issues without mandatory checklists and proper title prefix will be closed.
