### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by guidi** [nishad/udemy-dl#6]
I'm experiencing the following error.

Downloading 001 Introdução.mp4
Traceback (most recent call last):
  File "/usr/bin/udemy-dl", line 5, in <module>
    main()
  File "/usr/lib/python2.6/site-packages/udemy_dl/udemy_dl.py", line 229, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir)
  File "/usr/lib/python2.6/site-packages/udemy_dl/udemy_dl.py", line 170, in udemy_dl
    get_video(directory, filename, video['video_url'])
  File "/usr/lib/python2.6/site-packages/udemy_dl/udemy_dl.py", line 143, in get_video
    mkdir(directory)
  File "/usr/lib/python2.6/site-packages/udemy_dl/udemy_dl.py", line 136, in mkdir
    if not os.path.exists(directory):
  File "/usr/lib/python2.6/genericpath.py", line 18, in exists
    st = os.stat(path)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 45-46: ordinal not in range(128)

**Comment by nishad** [comment]
It seems like this tool is not working for you, please stop using this tool and try to find any other alternatives.
