### ISSUE TITLE
[PROPOSAL] udemy business enhancement 

### ISSUE THREAD

**Issue by GMags** [nishad/udemy-dl#65]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [y ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [y ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ y] I have checked that the issue I'm posting isn't already reported.
- [ y] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [y ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ y] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here, replace this line with your issue content}

Firstly great work on this utility.

I was wondering if it was possible to add an enhancement where this utility would also work with udemy business account where the user would be passing url's similar to the below:

https://business.udemy.com/     or https://<company_name>.udemy.com

**Comment by nishad** [comment]
* Unfortunately, I don't have access for  `https://business.udemy.com/ `
* `https://.udemy.com` is not a valid URL, could you explain it's significance ?

**Comment by GMags** [comment]
sorry i was asking if functionality could be added to support downloading of videos from udemy business accounts. for example i currently have access to business accounts such as: https://citigroup.udemy.com/home/my-courses/learning

obviousily you won't be able to access this url without credentials, but you may notice from the url that the name of the company name is at the beginning of the url

**Comment by nishad** [comment]
I'm getting your suggestion, **`*.udemy.com`** is a better representation for wildcard domains. Most of these business accounts are using extended authentication as well, so I cannot predict its success. However I'll add custom debug option in a future release to let you explore the possibilities.

**Comment by nishad** [comment]
@GMags, I've edited https://github.com/nishad/udemy-dl/issues/65#issuecomment-202474973, due to security and privacy concerns.

**Comment by GMags** [comment]
ok thanks, appreciate it.

**Comment by zabbal** [comment]
#81 is duplicate - was hard to grasp whta it's about from the title.
In my case there seems to be no extra auth besides usual login/pass.
I'll try to adjust regexp and report back my findings.

**Comment by mukhlesur-millon** [comment]
can you please give a course link?

**Comment by GMags** [comment]
a sample course link is as below, however i won’t be able to provide the authentication details.

https://citigroup.udemy.com/the-complete-ruby-on-rails-developer-course/learn/v4/overview

**Comment by mukhlesur-millon** [comment]
you can now delete it @GMags

**Comment by mukhlesur-millon** [comment]
as each subdomain.udemy.com use different login site, it is not possible to add all site. project like `browser_cookie` can help us this case.

**Comment by saurabh73** [comment]
Any update on this??? Also it will be helpful if someone can suggest build window-exe from source file.

**Comment by iamsmith41** [comment]
Hi,
I need assistance here:
I have **udemy-dl-windows-2.1.2**
I can see the different python scripts being called inside this.
My moto is to modify the script as below:
1. It asks me/prompts me  for two url inputs to create two arrays to store the two urls-
    a. one url   **https://company.udemy.com**   b. second one, the actual download url page   
        **https://company.udemy.com/COURSE_NAME**

2. It asks for login credentials (as it does) using first url, just to login to **company.udemy.com**
2. It should be saving the credential as it already does.
3. It uses second array/url now as it does to download the contents.

I tried modifying the script-  where https://www.udemy.com was mentioned to check syntax, I made it https://company.udemy.com/ but still throwing the error as I pasted in #198 

Thanks to correct me.
https://www.udemy.com/course_name   and https://comany.udemy.com/course_name  are simlar in view and content.  so there should not be any problem, I think.

**Comment by iamsmith41** [comment]
I just use username and password to login to my business account and done. So specific to my case, your assistance can make it work.

**Comment by iamsmith41** [comment]
Hi,

Kindly assist in this.

I changed the url to this-
https://company.udemy.com/course_name  ---------> https://www.udemy.com/course_name

I used the changed one for one course -
**udemy-dl.exe https://www.udemy.com/course_name1 -u user -p pass**

and it successfully downloaded the whole course.

When I am trying for another courses, for most of them I am getting -

```
[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 12345678
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 705, in udemy_dl
  File "<string>", line 382, in get_data_links
**KeyError: u'results'**
None
udemy_dl returned -1

```

For some others I am getting -
```
[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 735204
Getting course data: 1.15% [--------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 1.72% [--------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 2.87% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 3.45% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 4.02% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 4.60% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 5.17% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 5.75% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 6.32% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 6.90% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 7.47% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 8.05% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 8.62% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 9.20% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 9.77% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 10.34% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 10.92% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 12.64% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 13.22% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 13.79% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 14.37% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 14.94% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 16.67% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 17.24% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 17.82% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 18.39% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 18.97% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 19.54% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 20.11% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 20.69% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 21.26% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 22.99% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 23.56% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 24.14% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 24.71% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 25.29% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 27.01% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 27.59% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 28.16% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 28.74% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 29.31% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 29.89% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 31.61% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 32.18% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 32.76% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 33.33% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 33.91% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 35.63% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 36.21% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 36.78% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 37.36% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 37.93% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 38.51% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 39.08% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 39.66% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 40.23% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 40.80% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 41.38% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 43.10% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 43.68% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 44.25% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 44.83% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 45.40% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 45.98% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 46.55% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 47.13% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 47.70% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 48.28% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 50.00% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 50.57% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 51.15% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 51.72% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 52.30% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 52.87% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 53.45% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 54.02% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 54.60% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 55.17% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 55.75% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 56.32% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 56.90% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 57.47% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 58.05% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 58.62% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 59.20% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 59.77% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 60.34% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 62.07% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 62.64% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 63.22% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 63.79% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 64.37% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 64.94% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 65.52% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 66.09% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 66.67% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 67.24% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 67.82% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 68.39% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 68.97% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 69.54% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 71.26% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 71.84% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 72.41% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 72.99% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 73.56% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 74.14% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 74.71% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 75.29% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 75.86% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 76.44% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 77.01% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 77.59% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 78.16% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 78.74% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 80.46% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 81.03% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 81.61% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 82.18% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 82.76% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 83.33% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 83.91% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 85.63% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 86.21% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 86.78% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 87.36% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 87.93% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 89.66% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 90.23% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 90.80% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 91.38% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 91.95% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 92.53% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 93.10% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 93.68% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 94.25% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 94.83% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 95.40% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 95.98% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 96.55% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 97.13% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 97.70% [====================] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 98.28% [====================] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 98.85% [====================] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 99.43% [====================] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 100.00% [====================] Done
```

Kindly suggest for both errors.

**Comment by iamsmith41** [comment]
Hi,
Is udemy-dl support closed totally?
