### ISSUE TITLE
[Bug] TypeError: string indices must be integers

### ISSUE THREAD

**Issue by mahdi87gh** [nishad/udemy-dl#90]
Hi,
I just downloaded the tool and watched several youtube videos. After typing email nad password I get this error:

Traceback (most recent call last):
  File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\__main__.py", line 5, in <module>
    main()
  File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 289, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir, save_links)
  File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 209, in udemy_dl
    for video in get_video_links(course_id, lecture_start, lecture_end):
  File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 135, in get_video_links
    if item['__class'] == 'chapter':
TypeError: string indices must be integers

**Comment by nishad** [comment]
@mahdi87gh,

**All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
