### ISSUE TITLE
[BUG] TypeError trying to download

### ISSUE THREAD

**Issue by mahdi87gh** [nishad/udemy-dl#91]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Hi,
I just downloaded the tool and watched several youtube videos. After typing email and password I get this error:

```
Traceback (most recent call last):
File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 170, in run_module_as_main
"__main_", mod_spec)
File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl__main_.py", line 5, in 
main()
File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 289, in main
udemy_dl(username, password, link, lecture_start, lecture_end, output_dir, save_links)
File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 209, in udemy_dl
for video in get_video_links(course_id, lecture_start, lecture_end):
File "C:\Users\mahdi.ghorbanpour\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 135, in get_video_links
if item['__class'] == 'chapter':
TypeError: string indices must be integers
```

**Comment by mukhlesur-millon** [comment]
you are using older version. please upgrade from [here] (https://github.com/nishad/udemy-dl/wiki/Installing-development-version)

**Comment by mahdi87gh** [comment]
Thanks, I updated to that version. Now I'm getting this message :

Trying to log in ... and we're done.
Please Enroll in this course

and I don't know how to do that?

**Comment by nishad** [comment]
You can download only those courses you are enrolled in.

**Comment by mahdi87gh** [comment]
Is there anyway to download paid courses?

**Comment by nishad** [comment]
Yes, buy that course and enroll, after that you can download

**Comment by mahdi87gh** [comment]
That's not what I'm looking for :-(
If I had bought that course, I coul download videos by IDM anyway.

**Comment by nishad** [comment]
**`udemy-dl` is not intended to breach any udemy copyrights or it's business model. This tool is developed and maintained for legitimate users to keep an offline version of courses they purchased, mainly videos. This issue tracker will not tolerate or entertain any such illegal, or unethical activities.**

Soon there will be a public **`Hall of Shame`** list, where all users who violate this ethical cause will be listed, and all issues reported by them will be ignored.

**Comment by morriesmena** [comment]
Hello I am trying to download this a course, but i have this error, Iam already updated and y aleady paid for it, I dowloaded athers of my courses but the error is just with this one:

Traceback (most recent call last):
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\download.py", line 38, in download
    aria2c_dl(link, filename)
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\download.py", line 86, in aria2c_dl
    subprocess.call(command)
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\__main__.py", line 8, in <module>
    main()
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 706, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 624, in get_data
    get_attached_file(file_dir, attached_info)
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 525, in get_attached_file
    check_downloaded(element['file'], dest_dir, downloader)
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 582, in check_downloaded
    download_status = download(link, tmp_file, update_progress, downloader_name)
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\download.py", line 52, in download
    urlopen_dl(link, filename, update_progress)
  File "C:\Users\Mauricio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\download.py", line 115, in urlopen_dl
    with open(filename, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '.\\attached_files\\021 Operadores de Comparación mayor que menor que...\\Ejercicio-6-2.pdf.tmp'
